# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_tests', '0002_auto_20150701_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompressorWidget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
