# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 18:24
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('widgy_mezzanine', '0002_create_widgycalloutwidget'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='widgypage',
            managers=[
                ('select_related_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
