# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0003_auto_20150730_1401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='form',
            options={'verbose_name': 'form', 'verbose_name_plural': 'form submissions'},
        ),
        migrations.AlterField(
            model_name='choicefield',
            name='ident',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='ident',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='form',
            name='ident',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='forminput',
            name='ident',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='form_ident',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='formvalue',
            name='field_ident',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='multiplechoicefield',
            name='ident',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='textarea',
            name='ident',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
