# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-15 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0004_auto_20171115_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailuserhandler',
            name='to_ident',
            field=models.UUIDField(null=True, verbose_name='to'),
        ),
        migrations.AlterField(
            model_name='formsubmission',
            name='form_ident',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='formvalue',
            name='field_ident',
            field=models.UUIDField(),
        ),
    ]
